### ISSUE TITLE
can not run diablo

### ISSUE THREAD

**Issue by Derow** [bottytools/botty#622]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

This bug happened after v0.7.0

**Describe the bug**

There is no should_buy_pots function in belt.py, which is needed in diablo.py function _cs_town_visit, the program will hangup in there .

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by mgleed** [comment]
Nice to finally get a legit bug report here. Will work on it in the coming days, thank you.

**Comment by sukram91** [comment]
Version: Precompiled v.0.7.1  (low end pc)
I have the same issue

Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 154, in start
  File "bot.py", line 174, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 488, in on_run_diablo
  File "run\diablo.py", line 473, in battle
  File "run\diablo.py", line 51, in _cs_town_visit
AttributeError: module 'inventory.belt' has no attribute 'should_buy_pots'

**Comment by mgleed** [comment]
@sukram91 and @Derow the fix is gonna be more taxing than I expected. Please just disable `cs_town_visits` for now if you're running chaos sanctuary.

**Comment by basedgod1** [comment]
I'm still getting errors with `cs_town_visits` off, both `kill_cs_trash=0` and `kill_cs_trash=1`

With `kill_cs_trash=0`:

```
 [0.7.1-dev 2022-03-16 22:53:04,276] DEBUG      Traverse: [602]
 Exception in thread Thread-7:
 Traceback (most recent call last):
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
     self.run()
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\threading.py", line 910, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\Rocky\botty\src\bot.py", line 154, in start
     self.trigger_or_stop('init')
   File "C:\Users\Rocky\botty\src\bot.py", line 174, in trigger_or_stop
     self.trigger(name, **kwargs)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
     return event.trigger(model, *args, **kwargs)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger
     return self.machine._process(func)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
     self._transition_queue[0]()
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
     return self._process(event_data)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
     if trans.execute(event_data):
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute
     event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
     self.callback(func, event_data)
   File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
     func(*event_data.args, **event_data.kwargs)
   File "C:\Users\Rocky\botty\src\bot.py", line 496, in on_run_diablo
     res = self._diablo.battle(not self._pre_buffed)
   File "C:\Users\Rocky\botty\src\run\diablo.py", line 475, in battle
     if not self._layoutcheck("A", "Vizier", "dia_a_layout", "layoutcheck_a", [610620], 0.81 , None, ["DIA_A2Y_LAYOUTCHECK0", "DIA_A2Y_LAYOUTCHECK1", "DIA_A2Y_LAYOUTCHECK2", "DIA_A2Y_LAYOUTCHECK4", "DIA_A2Y_LAYOUTCHECK5", "DIA_A2Y_LAYOUTCHECK6"], ["DIA_A1L_LAYOUTCHECK0", "DIA_A1L_LAYOUTCHECK4", "DIA_A1L_LAYOUTCHECK4LEFT", "DIA_A1L_LAYOUTCHECK1", "DIA_A1L_LAYOUTCHECK2", "DIA_A1L_LAYOUTCHECK3","DIA_A1L_LAYOUTCHECK4RIGHT","DIA_A1L_LAYOUTCHECK5"]): return False
   File "C:\Users\Rocky\botty\src\run\diablo.py", line 367, in _layoutcheck
     self._char.kill_cs_trash(trash_location)
   File "C:\Users\Rocky\botty\src\char\i_char.py", line 297, in kill_cs_trash
    raise ValueError("Diablo CS Trash is not implemented!")
 ValueError: Diablo CS Trash is not implemented!
```

And with `kill_cs_trash=1`:
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Rocky\botty\src\bot.py", line 154, in start
    self.trigger_or_stop('init')
  File "C:\Users\Rocky\botty\src\bot.py", line 174, in trigger_or_stop
    self.trigger(name, **kwargs)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger
    return self.machine._process(func)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
    self._transition_queue[0]()
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
    return self._process(event_data)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
    if trans.execute(event_data):
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "C:\Users\Rocky\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "C:\Users\Rocky\botty\src\bot.py", line 496, in on_run_diablo
    res = self._diablo.battle(not self._pre_buffed)
  File "C:\Users\Rocky\botty\src\run\diablo.py", line 455, in battle
    if not self._river_of_flames_trash(): return False
  File "C:\Users\Rocky\botty\src\run\diablo.py", line 232, in _river_of_flames_trash
    self._char.kill_cs_trash("rof_01")
  File "C:\Users\Rocky\botty\src\char\i_char.py", line 297, in kill_cs_trash
    raise ValueError("Diablo CS Trash is not implemented!")
ValueError: Diablo CS Trash is not implemented!

```

**Comment by Steve6030** [comment]
Issue can be closed.
Author confirmed in discord they were trying to run chaos with blizz sorc.

**Comment by holgerrrr** [comment]
Hi, I have a similar problem. I have the cs_town_visits 0 and kill_cs_trash 1 but I get the following error: 
[https://freeimage.host/i/WOh13u](url)

**Comment by mgleed** [comment]
> Hi, I have a similar problem. I have the cs_town_visits 0 and kill_cs_trash 1 but I get the following error: https://freeimage.host/i/WOh13u

Only works for hammerdin
